name: Test Plan

on:
  issues:
    types: [opened]

jobs:
  extract-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check label
        id: check_label
        run: |
          LABEL_FOUND=$(jq -r '.issue.labels[] | select(.name == "test_plan") | .name' < "$GITHUB_EVENT_PATH")
          echo "Label Found: $LABEL_FOUND"
          if [[ "$LABEL_FOUND" == "test_plan" ]]; then
            echo "label_found=true" >> $GITHUB_ENV
          else
            echo "label_found=false" >> $GITHUB_ENV
          fi

      - name: Extract details
        if: env.label_found == 'true'
        id: extract_details
        run: |
          ISSUE_TITLE=$(jq -r '.issue.title' < "$GITHUB_EVENT_PATH")
          ISSUE_BODY=$(jq -r '.issue.body' < "$GITHUB_EVENT_PATH")
          MAJOR_RELEASE=$(echo "$ISSUE_BODY" | grep -i 'Is this a major release?' | cut -d ':' -f2- | xargs)
          echo "Issue title: $ISSUE_TITLE"
          echo "Issue body: $ISSUE_BODY"
          echo "Major release: $MAJOR_RELEASE" 
